from __future__ import annotations

from typing import Any


# Declarative manuscript-statistics tasks.  The compute script treats missing
# columns as a skipped task, so future Fig.3-Fig.6 multiseed bundles can add
# panel-specific tasks incrementally without changing the computation core.
MANUSCRIPT_STAT_TASKS: list[dict[str, Any]] = [
    {
        "task_id": "fig1b_baseline_vs_chance",
        "figure_id": "fig1",
        "panel_id": "B",
        "panel_data": "fig1b_panel_data.csv",
        "task_type": "one_sample",
        "group_cols": ["condition"],
        "reference": 10.0,
        "claim": "Baseline recall exceeds digit-chance performance.",
    },
    {
        "task_id": "fig1c_layer_decode_vs_chance",
        "figure_id": "fig1",
        "panel_id": "C",
        "panel_data": "fig1c_panel_data.csv",
        "task_type": "one_sample",
        "group_cols": ["layer"],
        "reference": 10.0,
        "claim": "Delay-period layer states decode sample identity above chance.",
    },
    {
        "task_id": "fig1c_layer_decode_contrasts",
        "figure_id": "fig1",
        "panel_id": "C",
        "panel_data": "fig1c_panel_data.csv",
        "task_type": "paired",
        "factor_col": "layer",
        "pairs": [("layer2", "layer1"), ("layer3", "layer1")],
        "claim": "Deeper STSP layers carry stronger delay-period identity information than layer 1.",
    },
    {
        "task_id": "fig1d_error_condition_contrasts",
        "figure_id": "fig1",
        "panel_id": "D",
        "panel_data": "fig1d_panel_data.csv",
        "task_type": "paired",
        "factor_col": "condition",
        "pairs": [
            ("dynamic_intact", "static_frozen"),
            ("ux_trial_shuffle", "static_frozen"),
            ("dynamic_intact", "ux_trial_shuffle"),
        ],
        "claim": "Dynamic and shuffled STSP conditions alter error rates relative to static-frozen dynamics.",
    },
    {
        "task_id": "fig1e_error_composition_contrasts",
        "figure_id": "fig1",
        "panel_id": "E",
        "panel_data": "fig1e_panel_data.csv",
        "task_type": "paired",
        "factor_col": "condition",
        "group_cols": ["category"],
        "pairs": [("ux_trial_shuffle", "dynamic_intact")],
        "claim": "Trial-shuffling u/x states changes the composition of error targets.",
    },
    {
        "task_id": "fig2b_constituent_similarity_vs_zero",
        "figure_id": "fig2",
        "panel_id": "B",
        "panel_data": "fig2B_panel_data.csv",
        "task_type": "one_sample",
        "group_cols": ["condition"],
        "reference": 0.0,
        "claim": "The fused state remains positively similar to both constituent item states.",
    },
    {
        "task_id": "fig2c_true_vs_shuffled_pair",
        "figure_id": "fig2",
        "panel_id": "C",
        "panel_data": "fig2C_panel_data.csv",
        "task_type": "paired",
        "factor_col": "condition",
        "pairs": [("True pair", "Shuffled pair")],
        "claim": "True pairs have stronger pair-specific scores than shuffled controls.",
    },
    {
        "task_id": "fig2d_indices_vs_zero",
        "figure_id": "fig2",
        "panel_id": "D",
        "panel_data": "fig2D_panel_data.csv",
        "task_type": "one_sample",
        "group_cols": ["condition", "metric"],
        "reference": 0.0,
        "claim": "Whole-pair and beyond-linear indices are positive across network seeds.",
    },
    {
        "task_id": "fig2e_neutral_ping_composition",
        "figure_id": "fig2",
        "panel_id": "E",
        "panel_data": "fig2E_panel_data.csv",
        "task_type": "paired",
        "factor_col": "condition",
        "group_cols": ["category"],
        "pairs": [("S_AB", "S0"), ("S_AB", "S_A"), ("S_AB", "S_B")],
        "claim": "Neutral ping readout composition differs across restored boundary states.",
    },
    {
        "task_id": "fig2f_partial_cue_auc",
        "figure_id": "fig2",
        "panel_id": "F",
        "panel_data": "fig2F_panel_data.csv",
        "task_type": "curve_auc",
        "x_col": "keep_prob",
        "factor_col": "condition",
        "group_cols": ["target_item"],
        "pairs": [("S_AB", "S0"), ("S_AB", "S_A"), ("S_AB", "S_B")],
        "claim": "The fused state improves partial-cue completion for both target items across dropout levels.",
    },
    {
        "task_id": "fig2s3a_layer_wpri_vs_zero",
        "figure_id": "fig2_supp",
        "panel_id": "S3A",
        "panel_data": "fig2_suppS3A_panel_data.csv",
        "task_type": "one_sample",
        "group_cols": ["layer"],
        "reference": 0.0,
        "claim": "Layerwise WPRI remains positive.",
    },
    {
        "task_id": "fig2s3b_layer_residual_vs_zero",
        "figure_id": "fig2_supp",
        "panel_id": "S3B",
        "panel_data": "fig2_suppS3B_panel_data.csv",
        "task_type": "one_sample",
        "group_cols": ["layer"],
        "reference": 0.0,
        "claim": "Layerwise residual pair specificity remains positive.",
    },
    {
        "task_id": "fig2s3c_model_comparison",
        "figure_id": "fig2_supp",
        "panel_id": "S3C",
        "panel_data": "fig2_suppS3C_panel_data.csv",
        "task_type": "paired",
        "factor_col": "condition",
        "group_cols": ["layer"],
        "pairs": [("unconstrained_AB", "mean_AB"), ("convex_AB", "mean_AB"), ("sum_AB", "mean_AB")],
        "claim": "Richer fused-state models outperform constituent-only baselines.",
    },
    {
        "task_id": "fig2s3d_ping_amplitude_trend",
        "figure_id": "fig2_supp",
        "panel_id": "S3D",
        "panel_data": "fig2_suppS3D_panel_data.csv",
        "task_type": "trend_slope",
        "x_col": "x_value",
        "group_cols": ["condition"],
        "claim": "Ping readout changes systematically across the sweep parameter.",
    },
    {
        "task_id": "fig2s3e_completion_delay_slope",
        "figure_id": "fig2_supp",
        "panel_id": "S3E",
        "panel_data": "fig2_suppS3E_panel_data.csv",
        "task_type": "trend_slope",
        "x_col": "x_value",
        "group_cols": ["condition"],
        "claim": "Completion gain changes with delay.",
    },
    {
        "task_id": "fig3_curve_and_sequence_placeholders",
        "figure_id": "fig3",
        "panel_id": "*",
        "task_type": "auto_describe",
        "claim": "Future multiseed Fig.3 panels need curve, sequence, and mass-summary statistics.",
    },
    {
        "task_id": "fig4_overlap_perturbation_placeholders",
        "figure_id": "fig4",
        "panel_id": "*",
        "task_type": "auto_describe",
        "claim": "Future multiseed Fig.4 panels need trend, perturbation, and interaction statistics.",
    },
    {
        "task_id": "fig5_event_chain_placeholders",
        "figure_id": "fig5",
        "panel_id": "*",
        "task_type": "auto_describe",
        "claim": "Future multiseed Fig.5 panels need event-rate and perturbation-effect statistics.",
    },
    {
        "task_id": "fig6_overlap_gated_placeholders",
        "figure_id": "fig6",
        "panel_id": "*",
        "task_type": "auto_describe",
        "claim": "Future multiseed Fig.6 panels need regression, interaction, and model-comparison statistics.",
    },
]
